# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  batch: true
  branches:
    include:
    - develop

pr: none

resources:
- repo: self

variables:
  - group: docker-variables
  - group: deploy-variables
  - name: 'appName'
    value: 'syzygy'
  - name: 'chartName'
    value: 'hx-syzygy'
  - name: 'vmImageName'
    value: 'ubuntu-latest'
  - name: 'dockerfilePath'
    value: 'docker/app/Dockerfile'
  - name: 'imageRepository'
    value: 'syzygy'
  - name: 'tag'
    value: '$(Build.BuildNumber)'

stages:
- stage: UpdateBuildNumber
  jobs:
  - job: UpdateBuildNumber
    steps:
    - bash: |
        echo "##vso[build.updatebuildnumber]$(System.PullRequest.SourceBranch).$(Build.BuildNumber)"
      condition: eq(variables['Build.Reason'], 'PullRequest')
      name: SetPRBuildName
    - bash: |
          echo "##vso[build.updatebuildnumber]$(Build.SourceBranchName).$(Build.BuildNumber)"
      condition: ne(variables['Build.Reason'], 'PullRequest')
      name: SetBranchBuildName

- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    # - bash: printenv
    #   displayName: List environment variables
    - task: Docker@2
      displayName: Build image
      inputs:
        command: build
        buildContext: $(Build.Repository.LocalPath)
        Dockerfile: $(dockerfilePath)
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Push image
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - publish: helm/
      artifact: helm

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  # exclude from PR validations
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: $(deployEnvironment_1)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            name: bake
            displayName: Bake K8s manifests from Helm chart
            inputs:
              action: 'bake'
              helmChart: $(Pipeline.Workspace)/helm/$(chartName)
              releaseName: $(appName)
              overrides: |
                nodeSelector.agentpool:$(nodeSelectorAgentPool)
                image.repository:$(containerRegistry)/$(imageRepository)
                image.tag:$(Build.BuildNumber)
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: $(bake.manifestsBundle)
