apiVersion: v1
kind: Service
metadata:
  name: beee-syzygy
  labels:
    app: syzygy
    component: microservice
spec:
  ports:
  - name: 443-443
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: syzygy
  sessionAffinity: None
  type: ClusterIP
