kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: syzygy
  labels:
    component: microservice
    role: syzygy
spec:
  replicas: 2
  template:
    metadata:
      name: syzygy
      labels:
        app: syzygy
        env: stg
    spec:
      containers:
      - name: beee-syzygy
        image: gcr.io/linker-testing/beee-syzygy
        resources:
          requests:
            memory: "64Mi"
            cpu: "30m"
          limits: {}
        imagePullPolicy: Always
        ports:
        - name: syzygy
          containerPort: 80
      nodeSelector:
        type: node00
